version: '3'
services:
  example:
    container_name: example
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      # target: dev

networks:
  default:
    name: rom_network
    external: true