version: '3'
services:
  proxymanger:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'proxy-manager'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DB_MYSQL_HOST: "npm-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      DB_MYSQL_NAME: "npm"
      # Uncomment the line below if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy-manager/data:/data
      - ./proxy-manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - npm-db
  
  npm-db:
    image: 'mariadb:latest'
    container_name: npm-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    volumes:
      - ./npm-data/mysql:/var/lib/mysql:Z

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: http://admin.meusite.local
      KC_PROXY: edge
      KC_LOG_LEVEL: debug
      # OAUTH2_PROXY_PROVIDER: 'oidc'
      # OAUTH2_PROXY_CLIENT_ID: 'oauth2-proxy'
      # OAUTH2_PROXY_CLIENT_SECRET: '5ymAvtLNX5RPTH5ZYnG1IvXf3FQ8raNm'
      # OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      # OAUTH2_PROXY_OIDC_ISSUER_URL: 'https://auth.meusite.local/realms/master'
      # OAUTH2_PROXY_REDIRECT_URL: 'https://auth.meusite.local/oauth2/callback'
    volumes:
      - ./keycloak:/opt/keycloak/config
    command: [ "start-dev"]

  red:
    image: nginx:stable-alpine
    container_name: red
    volumes:
      - ./nginx/red.html:/usr/share/nginx/html/index.html
    command: [nginx-debug, '-g', 'daemon off;']

  blue:
    image: nginx:stable-alpine
    container_name: blue
    volumes:
      - ./nginx/blue.html:/usr/share/nginx/html/index.html
    command: [nginx-debug, '-g', 'daemon off;']

  green:
    image: nginx:stable-alpine
    container_name: green
    volumes:
      - ./nginx/green.html:/usr/share/nginx/html/index.html
    command: [nginx-debug, '-g', 'daemon off;']

networks:
#   npm-internal:
  npm-network:
    external: true

# 192.168.15.122       meusite.local
# 192.168.15.122       admin.meusite.local
# 192.168.15.122       auth.meusite.local
# 192.168.15.122       green.meusite.local
# 192.168.15.122       blue.meusite.local
# 192.168.15.122       red.meusite.local
# 192.168.15.122       nodejs.meusite.local
# 127.0.0.1       meusite.local
# 127.0.0.1       admin.meusite.local
# 127.0.0.1       auth.meusite.local
# 127.0.0.1       green.meusite.local
# 127.0.0.1       blue.meusite.local
# 127.0.0.1       red.meusite.local
# 127.0.0.1       nodejs.meusite.local