version: '3'
services:
  proxymanger:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'proxy-manager'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./proxy-manager/data:/data
      - ./proxy-manager/letsencrypt:/etc/letsencrypt

  keycloak:
    image: keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false
      KEYCLOAK_HTTP_PORT: 8080
      PROXY_ADDRESS_FORWARDING: true

    ports:
      - '8080:8080'
    volumes:
      - ./h2/:/opt/keycloak/data/h2/
      - ./keycloak/data:/opt/keycloak/data
    command: [ "start-dev"]

  red:
    image: nginx:stable-alpine
    container_name: red
    volumes:
      - ./nginx/red.html:/usr/share/nginx/html/index.html
    command: [nginx-debug, '-g', 'daemon off;']

  blue:
    image: nginx:stable-alpine
    container_name: blue
    ports:
      - '4080:80'
    volumes:
      - ./nginx/blue.html:/usr/share/nginx/html/index.html
    command: [nginx-debug, '-g', 'daemon off;']

  green:
    image: nginx:stable-alpine
    container_name: green
    volumes:
      - ./nginx/green.html:/usr/share/nginx/html/index.html
    command: [nginx-debug, '-g', 'daemon off;']

networks:
  default:
    name: rom_network
    external: true
